queue_rules:
  # Per-chart × semver queues
  - name: opentelemetry-collector-patch
    merge_method: squash
    update_method: merge
  - name: opentelemetry-collector-minor
    merge_method: squash
    update_method: merge
  - name: opentelemetry-collector-major
    merge_method: squash
    update_method: merge

  - name: opentelemetry-operator-patch
    merge_method: squash
    update_method: merge
  - name: opentelemetry-operator-minor
    merge_method: squash
    update_method: merge
  - name: opentelemetry-operator-major
    merge_method: squash
    update_method: merge

  - name: opentelemetry-demo-patch
    merge_method: squash
    update_method: merge
  - name: opentelemetry-demo-minor
    merge_method: squash
    update_method: merge
  - name: opentelemetry-demo-major
    merge_method: squash
    update_method: merge

  - name: opentelemetry-ebpf-patch
    merge_method: squash
    update_method: merge
  - name: opentelemetry-ebpf-minor
    merge_method: squash
    update_method: merge
  - name: opentelemetry-ebpf-major
    merge_method: squash
    update_method: merge

  - name: opentelemetry-kube-stack-patch
    merge_method: squash
    update_method: merge
  - name: opentelemetry-kube-stack-minor
    merge_method: squash
    update_method: merge
  - name: opentelemetry-kube-stack-major
    merge_method: squash
    update_method: merge

  - name: opentelemetry-target-allocator-patch
    merge_method: squash
    update_method: merge
  - name: opentelemetry-target-allocator-minor
    merge_method: squash
    update_method: merge
  - name: opentelemetry-target-allocator-major
    merge_method: squash
    update_method: merge

pull_request_rules:
  # opentelemetry-collector
  - name: Route to opentelemetry-collector-patch queue
    conditions:
      - base=main
      - label=chart:opentelemetry-collector
      - label=semvertype:patch
      - status-success=PR SemVer label check
      - status-success=PR generation check
    actions:
      queue:
        name: opentelemetry-collector-patch
  - name: Route to opentelemetry-collector-minor queue
    conditions:
      - base=main
      - label=chart:opentelemetry-collector
      - label=semvertype:minor
      - status-success=PR SemVer label check
      - status-success=PR generation check
    actions:
      queue:
        name: opentelemetry-collector-minor
  - name: Route to opentelemetry-collector-major queue
    conditions:
      - base=main
      - label=chart:opentelemetry-collector
      - label=semvertype:major
      - status-success=PR SemVer label check
      - status-success=PR generation check
    actions:
      queue:
        name: opentelemetry-collector-major

  # opentelemetry-operator
  - name: Route to opentelemetry-operator-patch queue
    conditions:
      - base=main
      - label=chart:opentelemetry-operator
      - label=semvertype:patch
      - status-success=PR SemVer label check
      - status-success=PR generation check
    actions:
      queue:
        name: opentelemetry-operator-patch
  - name: Route to opentelemetry-operator-minor queue
    conditions:
      - base=main
      - label=chart:opentelemetry-operator
      - label=semvertype:minor
      - status-success=PR SemVer label check
      - status-success=PR generation check
    actions:
      queue:
        name: opentelemetry-operator-minor
  - name: Route to opentelemetry-operator-major queue
    conditions:
      - base=main
      - label=chart:opentelemetry-operator
      - label=semvertype:major
      - status-success=PR SemVer label check
      - status-success=PR generation check
    actions:
      queue:
        name: opentelemetry-operator-major

  # opentelemetry-demo
  - name: Route to opentelemetry-demo-patch queue
    conditions:
      - base=main
      - label=chart:opentelemetry-demo
      - label=semvertype:patch
      - status-success=PR SemVer label check
      - status-success=PR generation check
    actions:
      queue:
        name: opentelemetry-demo-patch
  - name: Route to opentelemetry-demo-minor queue
    conditions:
      - base=main
      - label=chart:opentelemetry-demo
      - label=semvertype:minor
      - status-success=PR SemVer label check
      - status-success=PR generation check
    actions:
      queue:
        name: opentelemetry-demo-minor
  - name: Route to opentelemetry-demo-major queue
    conditions:
      - base=main
      - label=chart:opentelemetry-demo
      - label=semvertype:major
      - status-success=PR SemVer label check
      - status-success=PR generation check
    actions:
      queue:
        name: opentelemetry-demo-major

  # opentelemetry-ebpf
  - name: Route to opentelemetry-ebpf-patch queue
    conditions:
      - base=main
      - label=chart:opentelemetry-ebpf
      - label=semvertype:patch
      - status-success=PR SemVer label check
      - status-success=PR generation check
    actions:
      queue:
        name: opentelemetry-ebpf-patch
  - name: Route to opentelemetry-ebpf-minor queue
    conditions:
      - base=main
      - label=chart:opentelemetry-ebpf
      - label=semvertype:minor
      - status-success=PR SemVer label check
      - status-success=PR generation check
    actions:
      queue:
        name: opentelemetry-ebpf-minor
  - name: Route to opentelemetry-ebpf-major queue
    conditions:
      - base=main
      - label=chart:opentelemetry-ebpf
      - label=semvertype:major
      - status-success=PR SemVer label check
      - status-success=PR generation check
    actions:
      queue:
        name: opentelemetry-ebpf-major

  # opentelemetry-kube-stack
  - name: Route to opentelemetry-kube-stack-patch queue
    conditions:
      - base=main
      - label=chart:opentelemetry-kube-stack
      - label=semvertype:patch
      - status-success=PR SemVer label check
      - status-success=PR generation check
    actions:
      queue:
        name: opentelemetry-kube-stack-patch
  - name: Route to opentelemetry-kube-stack-minor queue
    conditions:
      - base=main
      - label=chart:opentelemetry-kube-stack
      - label=semvertype:minor
      - status-success=PR SemVer label check
      - status-success=PR generation check
    actions:
      queue:
        name: opentelemetry-kube-stack-minor
  - name: Route to opentelemetry-kube-stack-major queue
    conditions:
      - base=main
      - label=chart:opentelemetry-kube-stack
      - label=semvertype:major
      - status-success=PR SemVer label check
      - status-success=PR generation check
    actions:
      queue:
        name: opentelemetry-kube-stack-major

  # opentelemetry-target-allocator
  - name: Route to opentelemetry-target-allocator-patch queue
    conditions:
      - base=main
      - label=chart:opentelemetry-target-allocator
      - label=semvertype:patch
      - status-success=PR SemVer label check
      - status-success=PR generation check
    actions:
      queue:
        name: opentelemetry-target-allocator-patch
  - name: Route to opentelemetry-target-allocator-minor queue
    conditions:
      - base=main
      - label=chart:opentelemetry-target-allocator
      - label=semvertype:minor
      - status-success=PR SemVer label check
      - status-success=PR generation check
    actions:
      queue:
        name: opentelemetry-target-allocator-minor
  - name: Route to opentelemetry-target-allocator-major queue
    conditions:
      - base=main
      - label=chart:opentelemetry-target-allocator
      - label=semvertype:major
      - status-success=PR SemVer label check
      - status-success=PR generation check
    actions:
      queue:
        name: opentelemetry-target-allocator-major
