queue_rules:
  # Per-chart × semver queues
  - name: opentelemetry-collector-patch
    merge_method: squash
    update_method: merge
  - name: opentelemetry-collector-minor
    merge_method: squash
    update_method: merge
  - name: opentelemetry-collector-major
    merge_method: squash
    update_method: merge

  - name: opentelemetry-operator-patch
    merge_method: squash
    update_method: merge
  - name: opentelemetry-operator-minor
    merge_method: squash
    update_method: merge
  - name: opentelemetry-operator-major
    merge_method: squash
    update_method: merge

  - name: opentelemetry-demo-patch
    merge_method: squash
    update_method: merge
  - name: opentelemetry-demo-minor
    merge_method: squash
    update_method: merge
  - name: opentelemetry-demo-major
    merge_method: squash
    update_method: merge

  - name: opentelemetry-ebpf-patch
    merge_method: squash
    update_method: merge
  - name: opentelemetry-ebpf-minor
    merge_method: squash
    update_method: merge
  - name: opentelemetry-ebpf-major
    merge_method: squash
    update_method: merge

  - name: opentelemetry-kube-stack-patch
    merge_method: squash
    update_method: merge
  - name: opentelemetry-kube-stack-minor
    merge_method: squash
    update_method: merge
  - name: opentelemetry-kube-stack-major
    merge_method: squash
    update_method: merge

  - name: opentelemetry-target-allocator-patch
    merge_method: squash
    update_method: merge
  - name: opentelemetry-target-allocator-minor
    merge_method: squash
    update_method: merge
  - name: opentelemetry-target-allocator-major
    merge_method: squash
    update_method: merge

pull_request_rules:
  - name: Route to opentelemetry-collector queue
    conditions:
      - base=main
      - label=chart:opentelemetry-collector
      - label~=^semvertype:(patch|minor|major)$
      - status-success=PR SemVer label check
      - status-success=PR generation check
    actions:
      queue:
        name: opentelemetry-collector-{{ label|replace('semvertype:', '') | lower }}

  - name: Route to opentelemetry-operator queue
    conditions:
      - base=main
      - label=chart:opentelemetry-operator
      - label~=^semvertype:(patch|minor|major)$
      - status-success=PR SemVer label check
      - status-success=PR generation check
    actions:
      queue:
        name: opentelemetry-operator-{{ label|replace('semvertype:', '') | lower }}

  - name: Route to opentelemetry-demo queue
    conditions:
      - base=main
      - label=chart:opentelemetry-demo
      - label~=^semvertype:(patch|minor|major)$
      - status-success=PR SemVer label check
      - status-success=PR generation check
    actions:
      queue:
        name: opentelemetry-demo-{{ label|replace('semvertype:', '') | lower }}

  - name: Route to opentelemetry-ebpf queue
    conditions:
      - base=main
      - label=chart:opentelemetry-ebpf
      - label~=^semvertype:(patch|minor|major)$
      - status-success=PR SemVer label check
      - status-success=PR generation check
    actions:
      queue:
        name: opentelemetry-ebpf-{{ label|replace('semvertype:', '') | lower }}

  - name: Route to opentelemetry-kube-stack queue
    conditions:
      - base=main
      - label=chart:opentelemetry-kube-stack
      - label~=^semvertype:(patch|minor|major)$
      - status-success=PR SemVer label check
      - status-success=PR generation check
    actions:
      queue:
        name: opentelemetry-kube-stack-{{ label|replace('semvertype:', '') | lower }}

  - name: Route to opentelemetry-target-allocator queue
    conditions:
      - base=main
      - label=chart:opentelemetry-target-allocator
      - label~=^semvertype:(patch|minor|major)$
      - status-success=PR SemVer label check
      - status-success=PR generation check
    actions:
      queue:
        name: opentelemetry-target-allocator-{{ label|replace('semvertype:', '') | lower }}
